- name: 'Check if yay is installed'
  shell:
      cmd: yay --version 2>&1 | head -1 | cut -d '"' -f 2
  register: yay_version
  check_mode: false
  changed_when: false
  failed_when: yay_version.rc != 0 and yay_version.rc != 127

- name: Install yay
  block:
      - name: Clone Yay repo
        ansible.builtin.git:
            repo: 'https://aur.archlinux.org/yay.git'
            dest: "{{ lookup('env', 'HOME') }}/.yay"

      - name: Install Yay
        shell: "cd {{ lookup('env', 'HOME') }}/.yay && makepkg -si --noconfirm"

  when: "'command not found' in yay_version.stdout"
  tags:
      - install
      - core

- name: Install pacman packages
  become: true
  community.general.pacman:
      name: '{{ item }}'
      state: present
  with_items:
      - archiver
      - base-devel
      - bat
      - curl
      - fontconfig
      - git
      - gtk3
      - htop
      - p7zip
      - stow
      - sxiv # image viewer
      - tree
      - unrar
      - unzip
      - zip
  tags:
      - core
      - install

- name: Install Yay packages
  kewlfft.aur.aur:
      use: yay
      name:
          - pod2man
          - libxml
      state: present
  tags:
      - core
      - install

- name: Install fonts
  ansible.builtin.git:
      accept_hostkey: true
      repo: git@github.com:amahmod/fonts.git
      dest: ~/.local/share/fonts
  tags:
      - install
      - core
      - fonts

- name: Update font cache
  shell: fc-cache -fv
  tags:
      - install
      - core
      - fonts
