- name: Clone Yay repo
  ansible.builtin.git:
      repo: 'https://aur.archlinux.org/yay.git'
      dest: "{{ lookup('env', 'HOME') }}/.yay"
  tags:
      - core
      - install

- name: Install Yay (aur helper)
  shell: "cd {{ lookup('env', 'HOME') }}/.yay && makepkg -si --noconfirm"
  tags:
      - core
      - install

- name: Install core packages
  kewlfft.aur.aur:
      use: yay
      name:
          - archiver
          - base-devel
          - bat
          - curl
          - fd
          - fontconfig
          - fzf
          - git
          - htop
          - jq
          - libnotify
          - p7zip
          - pod2man
          - ripgrep
          - stow
          - trash-cli
          - tree
          - unclutter
          - unrar
          - unzip
          - wget
          - xclip
          - zip
      state: present
  tags:
      - core
      - install
