- name: Install build tools
  become: true
  apt:
      name: '{{ item }}'
      state: present
  with_items:
      - curl
      - git
      - build-essential
      - libssl-dev
      - cmake
      - pkg-config
      - gettext
      - fontconfig
  tags:
      - install
      - core

- name: Create fonts directory
  file:
      path: ~/.local/share/fonts
      state: directory
  tags:
      - install
      - core
      - fonts

- name: Install fonts
  ansible.builtin.git:
      accept_hostkey: true
      repo: git@github.com:amahmod/fonts.git
      dest: ~/.local/share/fonts
  tags:
      - install
      - core
      - fonts

- name: Update font cache
  shell: fc-cache -fv
  tags:
      - install
      - core
      - fonts
