- name: Install build tools
  become: true
  apt:
      name: '{{ item }}'
      state: present
  with_items:
      - curl
      - git
      - build-essential
      - libssl-dev
      - cmake
      - pkg-config
      - gettext
      - fontconfig
      - fzf
  tags:
      - install
      - core

- name: Create fonts directory
  file:
      path: ~/.local/share/fonts
      state: directory
  tags:
      - install
      - core
      - fonts

- name: Install fonts
  ansible.builtin.git:
      accept_hostkey: true
      repo: git@github.com:amahmod/fonts.git
      dest: ~/.local/share/fonts
  tags:
      - install
      - core
      - fonts

- name: Update font cache
  shell: fc-cache -fv
  tags:
      - install
      - core
      - fonts

- name: Install lazygit
  become: true
  shell: |
      LAZYGIT_VERSION=$(curl -s "https://api.github.com/repos/jesseduffield/lazygit/releases/latest" | grep -Po '"tag_name": *"v\K[^"]*')
      curl -Lo /tmp/lazygit.tar.gz "https://github.com/jesseduffield/lazygit/releases/download/v${LAZYGIT_VERSION}/lazygit_${LAZYGIT_VERSION}_Linux_x86_64.tar.gz"
      tar xf /tmp/lazygit.tar.gz -C /tmp lazygit
      install /tmp/lazygit -D -t /usr/local/bin
      rm -f /tmp/lazygit.tar.gz /tmp/lazygit
  tags:
      - install
      - core
      - lazygit
