- name: Clone Yay repo
  ansible.builtin.git:
      repo: 'https://aur.archlinux.org/yay.git'
      dest: "{{ lookup('env', 'HOME') }}/.yay"
  tags:
      - core
      - install
      - neovim

- name: Install Yay
  shell: "cd {{ lookup('env', 'HOME') }}/.yay && makepkg -si --noconfirm"
  tags:
      - core
      - install
      - neovim

- name: Install pacman packages
  become: true
  community.general.pacman:
      name: '{{ item }}'
      state: present
  with_items:
      - base-devel
      - bat
      - curl
      - fontconfig
      - git
      - htop
      - p7zip
      - stow
      - tree
      - unrar
      - unzip
      - xclip
      - zip
  tags:
      - core
      - install
      - neovim

- name: Install Yay packages
  kewlfft.aur.aur:
      use: yay
      name:
          - pod2man
          - archiver
      state: present
  tags:
      - core
      - install
      - neovim

- name: Install fonts
  ansible.builtin.git:
      accept_hostkey: true
      repo: git@github.com:amahmod/fonts.git
      dest: ~/.local/share/fonts
  tags:
      - core
      - fonts
      - install

- name: Update font cache
  shell: fc-cache -fv
  tags:
      - core
      - fonts
      - install
