- name: Install stow
  become: true
  community.general.pacman:
    name: stow
    state: present
  tags:
    - dotfiles
    - install

- name: Check if dotfiles exist
  ansible.builtin.stat:
    path: "{{ lookup('env', 'HOME') }}/{{ item }}"
  register: dotfile_stat
  loop:
    - .zshrc
    - .bashrc
  tags:
    - dotfiles
    - install

- name: Backup dotfiles
  ansible.builtin.command: mv {{ lookup('env', 'HOME') }}/{{ item.item }} {{ lookup('env', 'HOME') }}/{{ item.item }}.old
  when: item.stat.exists
  loop: "{{ dotfile_stat.results }}"
  tags:
    - dotfiles
    - install

- name: Stow dotfiles
  ansible.builtin.command: "{{ playbook_dir }}/install_dotfiles"
  tags:
    - dotfiles
    - install
