- name: Install stow
  become: true
  community.general.pacman:
      name: stow
      state: present
  tags:
      - dotfiles
      - install

- name: Cloning .dotfiles
  ansible.builtin.git:
      accept_hostkey: true
      dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
      recursive: true
      repo: 'git@github.com:amahmod/.dotfiles.git'
      track_submodules: true
      update: true
      version: hyprland
  tags:
      - install
      - dotfiles

- name: Remove old .zshrc
  shell: mv ~/.zshrc ~/.zshrc.bak
  tags:
      - install
      - dotfiles

- name: Stow dotfiles
  shell: cd $HOME/.dotfiles && ./install
  tags:
      - install
      - dotfiles
