- name: Install stow
  become: true
  apt:
      name: stow
      state: present
  tags:
      - dotfiles
      - install

- name: Cloning .dotfiles
  ansible.builtin.git:
      repo: 'git@github.com:amahmod/.dotfiles.git'
      dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
      recursive: yes
      update: yes
      accept_hostkey: yes
      version: popos
  tags:
      - install
      - dotfiles

- name: Remove default .zshrc since it conflicst with stow
  copy: remote_src=True src=~/.zshrc dest=~/.zshrc.old
  tags:
      - install
      - dotfiles

- name: Stow dotfiles
  shell: cd $HOME/.dotfiles && ./install
  tags:
      - install
      - dotfiles
