- name: Install stow
  become: true
  community.general.pacman:
      name: stow
      state: present
  tags:
      - dotfiles
      - install

- name: Remove existing .dotfiles directory if exists
  ansible.builtin.file:
      path: "{{ lookup('env', 'HOME') }}/.dotfiles"
      state: absent
  tags:
      - dotfiles
      - install

- name: Create .dotfiles directory
  ansible.builtin.file:
      path: "{{ lookup('env', 'HOME') }}/.dotfiles"
      state: directory
      mode: '0755'
  tags:
      - dotfiles
      - install

- name: Copy dotfiles to home directory
  ansible.builtin.copy:
      src: '{{ playbook_dir }}/dotfiles/'
      dest: "{{ lookup('env', 'HOME') }}/.dotfiles/"
      mode: preserve
  tags:
      - dotfiles
      - install

- name: Check if .zshrc exists
  ansible.builtin.stat:
      path: "{{ lookup('env', 'HOME') }}/.zshrc"
  register: zshrc_stat
  tags:
      - dotfiles
      - install

- name: Backup old .zshrc
  ansible.builtin.command: mv {{ lookup('env', 'HOME') }}/.zshrc {{ lookup('env', 'HOME') }}/.zshrc.old
  when: zshrc_stat.stat.exists
  tags:
      - dotfiles
      - install

- name: Stow dotfiles
  shell: cd $HOME/.dotfiles && ./install
  tags:
      - dotfiles
      - install
