- name: Install stow
  become: true
  community.general.pacman:
      name: stow
      state: present
  tags:
      - dotfiles
      - install

- name: Check if .zshrc exists
  ansible.builtin.stat:
      path: "{{ lookup('env', 'HOME') }}/.zshrc"
  register: zshrc_stat
  tags:
      - dotfiles
      - install

- name: Backup old .zshrc
  ansible.builtin.command: mv {{ lookup('env', 'HOME') }}/.zshrc {{ lookup('env', 'HOME') }}/.zshrc.old
  when: zshrc_stat.stat.exists
  tags:
      - dotfiles
      - install

- name: Stow dotfiles
  ansible.builtin.command: '{{ playbook_dir }}/install_dotfiles'
  tags:
      - dotfiles
      - install
