- name: Setup node 16 source
  become: true
  shell: curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
  tags: &tags_for_node ['install', 'node', 'neovim']

- name: Install nodejs and npm
  become: true
  apt:
      name: ['nodejs']
      state: present
  tags: *tags_for_node

- name: npmjs prefix
  file:
      path: ~/.local/.npm-packages
      state: directory
  tags: *tags_for_node

- name: npmjs global settings
  shell: npm config set prefix '~/.local/.npm-packages'
  tags: *tags_for_node

- name: add npm global to PATH
  shell: export PATH=~/.local/.npm-packages/bin:$PATH
  tags: *tags_for_node

- name: Install global npm packages
  npm:
      global: yes
      name: '{{ item }}'
  with_items:
      - n
      - nodemon
      - yarn
      - typescript
      - ts-node
      - live-server
  tags: *tags_for_node
