- name: Install node 16
  become: true
  community.general.pacman:
      name: nodejs-lts-iron
      state: present
  tags: &tags_for_node ['install', 'node', 'neovim']

- name: Install npm
  become: true
  community.general.pacman:
      name: npm
      state: present
  tags: *tags_for_node

- name: npmjs prefix
  file:
      path: ~/.local/.npm-packages
      state: directory
  tags: *tags_for_node

- name: npmjs global settings
  shell: npm config set prefix '~/.local/.npm-packages'
  tags: *tags_for_node

- name: add npm global to PATH
  shell: export PATH=~/.local/.npm-packages/bin:$PATH
  tags: *tags_for_node

- name: Install global npm packages
  npm:
      global: yes
      name: '{{ item }}'
  with_items:
      - '@fsouza/prettierd'
      - eslint_d
      - live-server
      - neovim
      - nodemon
      - prettier
      - ts-node
      - typescript
      - yarn
  tags: *tags_for_node
