- name: Install luarocks
  become: true
  apt:
      name: luarocks
      state: present
  tags:
      - install
      - neovim

- name: Install tree-sitter
  npm:
      name: tree-sitter
      state: present
      global: yes
  tags:
      - install
      - neovim

- name: Check if nvim is installed
  shell:
      cmd: nvim -version 2>&1 | head -1 | cut -d '"' -f 2
  register: nvim_version
  failed_when: nvim_version.rc != 0 and nvim_version.rc != 127

- name: Remove neovim
  shell: rm -rf ~/neovim

- name: Get Packer
  ansible.builtin.git:
      repo: 'https://github.com/wbthomason/packer.nvim'
      dest: "{{ lookup('env', 'HOME') }}/.local/share/nvim/site/pack/packer/start/packer.nvim"

- name: Clone Neovim
  ansible.builtin.git:
      repo: 'https://github.com/neovim/neovim.git'
      dest: "{{ lookup('env', 'HOME') }}/neovim"

- name: Build neovim
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && make -j 20"

- name: Install neovim
  become: true
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && make install"
  tags:
      - install
      - neovim

- name: Install required packages for neovim
  npm:
      global: yes
      name: '{{ item }}'
  with_items:
      - neovim
      - typescript
      - '@fsouza/prettierd'
      - prettier
      - eslint_d
      - luacheck
  tags:
      - install
      - neovim
