- name: Install tree-sitter
  become: true
  community.general.pacman:
      name: tree-sitter
      state: present
  tags:
      - install
      - neovim

- name: Install required packages for neovim
  kewlfft.aur.aur:
      use: yay
      name: '{{ item }}'
      state: present
  with_items:
      - luacheck-git
      - prettierd
      - rust-analyzer
      - shellcheck
      - shfmt
      - stylua-git
      - yamllint
      - neovim
  tags:
      - install
      - neovim
