- name: Create user directories
  file:
    path: '{{ item }}'
    state: directory
  with_items:
    - "{{ lookup('env', 'HOME') }}/Desktop"
    - "{{ lookup('env', 'HOME') }}/Downloads"
    - "{{ lookup('env', 'HOME') }}/Documents/books"
    - "{{ lookup('env', 'HOME') }}/Pictures/screenshot"
    - "{{ lookup('env', 'HOME') }}/wokspace/client"
    - "{{ lookup('env', 'HOME') }}/wokspace/personal"
    - "{{ lookup('env', 'HOME') }}/wokspace/learning"
  tags:
    - install
    - wm

- name: Install wm packages
  become: true
  community.general.pacman:
    name: '{{ item }}'
    state: present
  with_items:
    - xorg
    - xorg-xinit
    - nvidia
    - nvidia-utils
    - arandr
    - bspwm
    - sxhkd
    - dmenu
    - picom
    - feh
    - dunst
    - libnotify
    - flameshot
    - zathura
    - calcurse
    - unclutter
    - ripgrep
    - fzf
    - trash-cli
    - redshift
    - thunar
    - thunar-archive-plugin
    - tumbler
    - ffmpegthumbnailer
    - neofetch
    - polybar
    - ibus
    - ibus-m17n
    - rofi
    - wezterm
    - ttf-roboto
  tags:
    - install
    - wm

- name: Install media apps
  become: true
  community.general.pacman:
    name: '{{ item }}'
    state: present
  with_items:
    - ffmpeg
    - sxiv
    - mpv
    - pulsemixer
    - alsa-utils
  tags:
    - install
    - wm

- name: Install aur packages
  kewlfft.aur.aur:
    use: yay
    state: present
    name: '{{ item }}'
  with_items:
    - zathura-pdf-mupdf
    - jmtpfs
    - lf-bin
    - ibus-avro-git
    - nerd-fonts-jetbrains-mono
    - gtk-theme-numix-solarized
    - luv-icon-theme-git
    - xcursor-numix
  tags:
    - install
    - wm
