- name: Create user directories
  file:
      path: '{{ item }}'
      state: directory
  with_items:
      - "{{ lookup('env', 'HOME') }}/Desktop"
      - "{{ lookup('env', 'HOME') }}/Downloads"
      - "{{ lookup('env', 'HOME') }}/Documents/books"
      - "{{ lookup('env', 'HOME') }}/Pictures/screenshots"
      - "{{ lookup('env', 'HOME') }}/work"
      - "{{ lookup('env', 'HOME') }}/personal"
      - "{{ lookup('env', 'HOME') }}/learning"
  tags:
      - install
      - wm

- name: Install wm packages
  become: true
  community.general.pacman:
      name: '{{ item }}'
      state: present
  with_items:
      - brightnessctl
      - calcurse
      - dmenu
      - dunst
      - firefox-developer-edition
      - flameshot
      - fzf
      - grim
      - gvfs
      - kitty
      - linux-headers
      - man
      - pipewire
      - polkit-gnome
      - qt5-wayland
      - qt6-wayland
      - ripgrep
      - thunar
      - thunar-archive-plugin
      - thunar-volman
      - trash-cli
      - tumbler
      - wireplumber
      - wofi
      - zathura
  tags:
      - install
      - wm

- name: Install aur packages
  kewlfft.aur.aur:
      use: yay
      state: present
      name: '{{ item }}'
  with_items:
      - cliphist
      - hyprland
      - hyprpicker-git
      - jmtpfs
      - lf-bin
      - nerd-fonts-jetbrains-mono
      - otf-font-awesome
      - otf-symbola
      - rofi-lbonn-wayland-git
      - swaybg
      - swayimg
      - thunar-dropbox
      - thunar-media-tags-plugin
      - xdg-desktop-portal-hyprland-git
      - waybar-hyprland-git
      - wlogout
      - swaylock
  tags:
      - install
      - wm

- name: Lf terminal file manager
  kewlfft.aur.aur:
      state: present
      use: yay
      name: '{{ item }}'
  with_items:
      - lf-bin
      - ctpv-git # file preview
  tags:
      - install
      - wm
      - lf

- name: Install media apps
  become: true
  community.general.pacman:
      name: '{{ item }}'
      state: present
  with_items:
      - alsa-utils
      - ffmpeg
      - mpv
      - pavucontrol
      - pulsemixer
      - pamixer
  tags:
      - install
      - wm
