- name: Create user directories
  file:
      path: '{{ item }}'
      state: directory
  with_items:
      - "{{ lookup('env', 'HOME') }}/Desktop"
      - "{{ lookup('env', 'HOME') }}/Downloads"
      - "{{ lookup('env', 'HOME') }}/Documents/books"
      - "{{ lookup('env', 'HOME') }}/Pictures/screenshot"
      - "{{ lookup('env', 'HOME') }}/wokspace/client"
      - "{{ lookup('env', 'HOME') }}/wokspace/personal"
      - "{{ lookup('env', 'HOME') }}/wokspace/learning"
  tags:
      - install
      - wm

- name: Install wm packages
  become: true
  community.general.pacman:
      name: '{{ item }}'
      state: present
  with_items:
      - dunst
      - zathura
      - calcurse
      - ripgrep
      - fzf
      - trash-cli
      - kitty
      - pipewire
      - wireplumber
      - polkit-kde-agent
      - qt5-wayland
      - qt6-wayland
      - firefox-developer-edition
      - man
  tags:
      - install
      - wm

- name: Install media apps
  become: true
  community.general.pacman:
      name: '{{ item }}'
      state: present
  with_items:
      - ffmpeg
      - mpv
      - pulsemixer
      - alsa-utils
      - pavucontrol
  tags:
      - install
      - wm

- name: Install aur packages
  kewlfft.aur.aur:
      use: yay
      state: present
      name: '{{ item }}'
  with_items:
      - cliphist
      - hyprland-nvidia-git
      - xdg-desktop-portal-hyprland-git
      - jmtpfs
      - lf-bin
      - otf-symbola
      - otf-font-awesome
      - gvfs
      - thunar
      - thunar-archive-plugin
      - thunar-media-tags-plugin
      - thunar-dropbox
      - thunar-vulman
      - nerd-fonts-jetbrains-mono
      - swaybg
      - swayimg
  tags:
      - install
      - wm
