- name: Install window manager packages
  kewlfft.aur.aur:
      use: yay
      name: '{{ item }}'
      state: present
  with_items:
      # Window Manager and Desktop Environment
      - bspwm # Tiling window manager
      - sxhkd # Simple X hotkey daemon
      - xorg # X Window System
      - xorg-xinit # X Window System initializer
      - picom # Compositor for X11
      - polybar # Status bar
      - rofi # Window switcher and launcher
      - rofi-emoji # Emoji selector for Rofi
      - dunst # Lightweight notification daemon

      # Display and Input
      - arandr # GUI for XRandR
      - ibus # Input method framework
      - ibus-avro-git # Bengali input method
      - ibus-m17n # Multilingual input method
      - xdotool # X11 automation tool

      # Themes and Icons
      - gtk-theme-numix-solarized # Solarized Numix GTK theme
      - numix-circle-icon-theme-git # Numix Circle icon theme
      - xcursor-numix # Numix cursor theme
  tags:
      - wm
      - install
