- name: Create user directories
  file:
      path: '{{ item }}'
      state: directory
  with_items:
      - "{{ lookup('env', 'HOME') }}/Desktop"
      - "{{ lookup('env', 'HOME') }}/Downloads"
      - "{{ lookup('env', 'HOME') }}/Documents/books"
      - "{{ lookup('env', 'HOME') }}/Pictures/screenshot"
      - "{{ lookup('env', 'HOME') }}/wokspace/client"
      - "{{ lookup('env', 'HOME') }}/wokspace/personal"
      - "{{ lookup('env', 'HOME') }}/wokspace/learning"
  tags:
      - install
      - wm

- name: Install wm packages
  become: true
  community.general.pacman:
      name: '{{ item }}'
      state: present
  with_items:
      - dunst
      - zathura
      - calcurse
      - ripgrep
      - fzf
      - trash-cli
      - kitty
      - pipewire
      - wireplumber
      - polkit-kde-agent
      - qt5-wayland
      - qt6-wayland
  tags:
      - install
      - wm

- name: Install media apps
  become: true
  community.general.pacman:
      name: '{{ item }}'
      state: present
  with_items:
      - ffmpeg
      - mpv
      - pulsemixer
      - alsa-utils
  tags:
      - install
      - wm

- name: Install aur packages
  kewlfft.aur.aur:
      use: yay
      state: present
      name: '{{ item }}'
  with_items:
      - hyprland-nvidia-git
      - jmtpfs
      - lf-bin
      - otf-symbola
  tags:
      - install
      - wm
