- name: Create user directories
  file:
      path: '{{ item }}'
      state: directory
  with_items:
      - "{{ lookup('env', 'HOME') }}/Desktop"
      - "{{ lookup('env', 'HOME') }}/Downloads"
      - "{{ lookup('env', 'HOME') }}/Documents/books"
      - "{{ lookup('env', 'HOME') }}/Pictures/screenshots"
      - "{{ lookup('env', 'HOME') }}/work"
      - "{{ lookup('env', 'HOME') }}/personal"
      - "{{ lookup('env', 'HOME') }}/learning"
  tags:
      - install
      - wm

- name: Install wm packages
  become: true
  community.general.pacman:
      name: '{{ item }}'
      state: present
  with_items:
      - arandr
      - bspwm
      - calcurse
      - dmenu
      - dunst
      - feh
      - ffmpegthumbnailer
      - flameshot
      - fzf
      - gvfs
      - ibus
      - ibus-m17n
      - libnotify
      - neofetch
      - polybar
      - redshift
      - ripgrep
      - rofi
      - sxhkd
      - thunar
      - thunar-archive-plugin
      - thunar-volman
      - trash-cli
      - ttf-roboto
      - tumbler
      - unclutter
      - wezterm
      - xorg
      - xorg-xinit
      - zathura
  tags:
      - install
      - wm

- name: Install media apps
  become: true
  community.general.pacman:
      name: '{{ item }}'
      state: present
  with_items:
      - alsa-utils
      - ffmpeg
      - mpv
      - pulsemixer
      - sxiv
  tags:
      - install
      - wm

- name: Install aur packages
  kewlfft.aur.aur:
      use: yay
      state: present
      name: '{{ item }}'
  with_items:
      - gtk-theme-numix-solarized
      - ibus-avro-git
      - jmtpfs
      - lf-bin
      - nerd-fonts-jetbrains-mono
      - numix-circle-icon-theme-git
      - otf-symbola
      - picom-animations-git
      - ttf-jetbrains-mono-nerd
      - xcursor-numix
      - zathura-pdf-mupdf
  tags:
      - install
      - wm

- name: Enable undercurl support in wezterm
  shell: tempfile=$(mktemp) \ && curl -o $tempfile https://raw.githubusercontent.com/wez/wezterm/main/termwiz/data/wezterm.terminfo \ && tic -x -o ~/.terminfo $tempfile \ && rm $tempfile
  tags:
      - install
      - wm
