- name: Create user directories
  file:
      path: '{{ item }}'
      state: directory
  with_items:
      - "{{ lookup('env', 'HOME') }}/Desktop"
      - "{{ lookup('env', 'HOME') }}/Downloads"
      - "{{ lookup('env', 'HOME') }}/Documents/books"
      - "{{ lookup('env', 'HOME') }}/Pictures/screenshots"
      - "{{ lookup('env', 'HOME') }}/work"
      - "{{ lookup('env', 'HOME') }}/personal"
      - "{{ lookup('env', 'HOME') }}/learning"
  tags:
      - install
      - wm

- name: Install wm packages
  become: true
  community.general.pacman:
      name: '{{ item }}'
      state: present
  with_items:
      - brightnessctl
      - calcurse
      - dmenu
      - dunst
      - firefox-developer-edition
      - fzf
      - grim
      - gvfs
      - kitty
      - man
      - pipewire
      - polkit-kde-agent
      - qt5-wayland
      - qt6-wayland
      - ripgrep
      - thunar
      - thunar-archive-plugin
      - thunar-volman
      - trash-cli
      - tumbler
      - wireplumber
      - zathura
      - linux-headers
      - nvidia-dkms
      - nvidia-settings
      - nvidia-utils
      - wofi
  tags:
      - install
      - wm

- name: Install aur packages
  kewlfft.aur.aur:
      use: yay
      state: present
      name: '{{ item }}'
  with_items:
      - cliphist
      - hyprland
      - hyprpicker-git
      - jmtpfs
      - lf-bin
      - nerd-fonts-jetbrains-mono
      - otf-font-awesome
      - otf-symbola
      - rofi-lbonn-wayland-git
      - swaybg
      - swayimg
      - thunar-dropbox
      - thunar-media-tags-plugin
      - xdg-desktop-portal-hyprland-git
      - waybar-hyprland-git
      - wlogout
      - swaylock
  tags:
      - install
      - wm

- name: Lf terminal file manager
  kewlfft.aur.aur:
      state: present
      use: yay
      name: '{{ item }}'
  with_items:
      - lf-bin
      - ctpv-git # file preview
  tags:
      - install
      - wm
      - lf

- name: Install media apps
  become: true
  community.general.pacman:
      name: '{{ item }}'
      state: present
  with_items:
      - alsa-utils
      - ffmpeg
      - mpv
      - pavucontrol
      - pulsemixer
      - pamixer
  tags:
      - install
      - wm

- name: 'Check if flameshoft is installed'
  shell:
      cmd: flameshoft --version 2>&1 | head -1 | cut -d '"' -f 2
  register: flameshot_version
  check_mode: false
  changed_when: false
  failed_when: flameshot_version.rc != 0 and flameshot_version.rc != 127
  tags:
      - install
      - flameshot
      - wm

- name: Install flameshot
  block:
      - name: Install dependencies
        become: true
        community.general.pacman:
            name:
                - cmake
                - base-devel
                - git
                - qt5-base
                - qt5-tools
                - qt5-svg
                - openssl
                - ca-certificates
            state: present

      - name: Remove existing code
        shell: rm -rf ~/.flameshot

      - name: Clone Flameshot repo
        ansible.builtin.git:
            repo: 'git@github.com:flameshot-org/flameshot.git'
            dest: "{{ lookup('env', 'HOME') }}/.flameshot"

      - name: Create build directory
        shell: "cd {{ lookup('env', 'HOME') }}/.flameshot && mkdir build"

      - name: Build flameshot
        shell: "cd {{ lookup('env', 'HOME') }}/.flameshot/build && cmake -DUSE_WAYLAND_GRIM=true ../"

      - name: Install flameshot
        become: true
        shell: "cd {{ lookup('env', 'HOME') }}/.flameshot/build && make install"
  when: "'command not found' in flameshot_version.stdout"
  tags:
      - install
      - flameshot
      - wm
