- name: Make sure curl is installed
  become: true
  community.general.pacman:
      name: curl
      state: present
  tags: &tags_for_zsh_tasks ['install', 'productivity', 'zsh']

- name: Install ZSH
  become: true
  community.general.pacman:
      name: zsh
      state: present
  tags: *tags_for_zsh_tasks

- name: Change shell to zsh
  become: true
  shell: chsh -s $(which zsh) ${whoami}
  tags: *tags_for_zsh_tasks

- name: Change shell to zsh
  become: true
  user:
      name: '{{ username }}'
      shell: /bin/zsh
  tags: *tags_for_zsh_tasks

- name: Check that the .oh-my-zsh exists
  stat:
      path: '/home/{{ username }}/.oh-my-zsh'
  register: oh_my_stats
  tags: *tags_for_zsh_tasks

- name: Oh-My-Zsh
  shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh > ~/.oh-my-installer && chmod +x ~/.oh-my-installer && ~/.oh-my-installer && rm ~/.oh-my-installer
  tags: *tags_for_zsh_tasks
  when: oh_my_stats.stat.exists == False
  become_user: amahmod

- name: Install zsh-autosuggestions
  ansible.builtin.git:
      repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
      dest: '~/.oh-my-zsh/plugins/zsh-autosuggestions'
  tags: *tags_for_zsh_tasks

- name: Install zsh-syntax-highlighting
  ansible.builtin.git:
      repo: 'https://github.com/zsh-users/zsh-syntax-highlighting'
      dest: '~/.oh-my-zsh/plugins/zsh-syntax-highlighting'
  tags: *tags_for_zsh_tasks
